# -*- coding: utf-8 -*-
"""Practical - 5 Cradit Card.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V5ssljms62PNR6UW4gX2d-6k1SWASWCh
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer

from google.colab import drive
drive.mount('/content/drive')

df=pd.read_csv('/content/drive/MyDrive/creditcard.csv')

df.head()

df.isnull().sum()

df.describe()

df_fraud = df[df['Class'] == 1]
number_fraud = len(df[df.Class == 1])
number_no_fraud = len(df[df.Class == 0])

number_fraud

number_no_fraud

plt.figure(figsize=(15,5))
plt.scatter(df_fraud['Time'], df_fraud['Amount'])
plt.title('Scratter plot amount fraud')
plt.xlabel('Time')
plt.ylabel('Amount')
plt.xlim([0,25000])
plt.ylim([0,2500])
plt.show()

df['V23'].fillna(value=df['V23'].mode()[0], inplace=True)
df['V24'].fillna(value=df['V24'].mode()[0], inplace=True)
df['V25'].fillna(value=df['V25'].mode()[0], inplace=True)
df['V26'].fillna(value=df['V26'].mode()[0], inplace=True)
df['V27'].fillna(value=df['V27'].mode()[0], inplace=True)
df['V28'].fillna(value=df['V28'].mode()[0], inplace=True)
df['Amount'].fillna(value=df['Amount'].mode()[0], inplace=True)
df['Class'].fillna(value=df['Class'].mode()[0], inplace=True)

# Splitting data into features (X) and target (y)
X = df.iloc[:, :-1]
y = df['Class']

# Splitting data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize numerical features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Instantiate logistic regression model
model = LogisticRegression()

# Train the model
model.fit(X_train, y_train)

# Instantiate the imputer with desired strategy (e.g., mean, median, etc.)
imputer = SimpleImputer(strategy='mean')

# Fit the imputer on the training data and transform both training and test data
X_train = imputer.fit_transform(X_train)
X_test = imputer.transform(X_test)

# Now, your data is free from NaN values, and you can proceed with making predictions using the original code
# Predictions on the test set
y_pred = model.predict(X_test)

# Confusion matrix and classification report
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

from sklearn.model_selection import GridSearchCV

# Define hyperparameters to tune
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100]}

# Instantiate logistic regression model
model = LogisticRegression()

# Grid search for hyperparameter tuning
grid_search = GridSearchCV(model, param_grid, cv=5)
grid_search.fit(X_train, y_train)

# Best hyperparameters
best_params = grid_search.best_params_
print(f"Best Hyperparameters: {best_params}")

# Evaluate the model with the best hyperparameters
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)
print(classification_report(y_test, y_pred))